google login
MentalJava/flufire-sample pull request #2
Opened 2024-06-20 15:38 UTC by MentalJava

구글 로그인 버튼 > 로그인 > 홈 화면

2024-06-21 01:15 UTC, kdjun97 requested changes
.

2024-06-21 01:15 UTC, kdjun97 commented on pubspec.lock
>  packages:
빌드할 때, 자동으로 만들어지는 파일들 혹은 이런 .lock 파일은 .gitignore를 활용해서 commit할 때 올라가지 않도록 설정하면 좋을 것 같아요.
.gitignore에 대해 찾아보면 좋을 것 같습니다
@MentalJava

2024-06-21 01:15 UTC, kdjun97 commented on lib/main.dart
> -  }
이런식으로 main에 다 때려넣는거 말고 파일 분리 하는거 좋습니다! @MentalJava 👍

2024-06-21 01:15 UTC, kdjun97 commented on lib/src/pages/login.dart
> +      body: Center(
로그인 버튼을 누르고, 로그인 처리가 될 때 까지 loading progressBar를 보여주면 좋을 것 같아요 @MentalJava

2024-06-21 05:05 UTC, MentalJava commented on lib/src/pages/login.dart
> +      body: Center(
네 알겠습니다 좋은 코멘트 감사드립니다 ㅎㅎ

2024-06-21 05:05 UTC, MentalJava commented on lib/main.dart
> -  }
칭찬 감사합니다 앞으로도 정진하는 개발자 되겠습니다 !

2024-06-21 05:05 UTC, MentalJava commented on pubspec.lock
>  packages:
오오 그런 방법이 ..! 참고해서 다시 해보겠습니다 ㅎㅎ 화이팅 !

2024-06-23 10:52 UTC, kdjun97 approved these changes
아주 좋습니다! 👍 @MentalJava

2024-06-23 10:52 UTC, kdjun97 commented on lib/src/pages/login.dart
> +  Future<void> signInWithGoogle() async {
로딩까지 넣으셨군요. 아주 좋습니다 👍 

setState를 사용하지 않고, GetX에서 제공해주는 GetBuilder, Obx, Obs 등을 이용해서 State Management 하는 법을 공부해봐도 좋을 것 같아요!
말씀드린 케이스는 StatelessWidget을 extends해도 작동한답니다. @MentalJava 

일단 해당 수정은 다른 브랜치를 파서 작업해도 좋을 것 같고, Approve는 누르고 이어서 해보시는걸 추천드립니다.

2024-06-23 10:57 UTC, MentalJava commented on lib/src/pages/login.dart
> +  Future<void> signInWithGoogle() async {
네 알겠습니다 ! 빠르게 다시 보여드리겠습니다 ㅎㅎ

2024-06-23 10:57 UTC, merged